const PILOT_OPTIONS = {
    BACKGROUNDS: [
        'Celebrity',
        'Colonist',
        'Criminal',
        'Far-field Team',
        'Hacker',
        'Mechanic',
        'Medic',
        'Mercenary',
        'NHPspecialist',
        'Noble',
        'Outlaw',
        'Penalcolonist',
        'Priest',
        'Scientist',
        'Soldier',
        'Spaceborn',
        'Specops',
        'Supersoldier',
        'Starshippilot',
        'Worker'
    ],
    SKILL_TRIGGER: [
        'Act Unseen or Unheard',
        'Apply fists to faces',
        'Assault',
        'Blow something up',
        'Charm',
        'Get a hold of something',
        'Get somewhere quickly',
        'Hack or fix',
        'Invent or create',
        'Investigate',
        'Lead or inspire',
        'Patch Up',
        'Pull rank',
        'Read a situation',
        'Show off',
        'Spot',
        'Stay cool',
        'Survive',
        'Take control',
        'Take someone out',
        'Threaten',
        'Word on the street'
    ],
    PILOT_GEAR: [
        {
            name: 'Corrective',
            tags: 'Limited 1 use',
            description: 'This clear, plastic-like sheet can be placed over the wounds of severely injured pilots. It instantly begins to stabilize them, injecting medicine and deploying nanites to stitch wounds shut.'
        },
        {
            name: 'Patch',
            tags: 'Limited 1 use',
            description: '“Patch” is pilot slang for any kind of modern first aid gear, including sprayable medi-gel and instant-acting medical patches.'
        },
        {
            name: 'Stims',
            tags: 'Limited 3 uses',
            description: 'These chemical stimulants are sometimes administered automatically by injectors built into a pilot’s suit, or even implanted within their body. Uncontrolled use can be addictive and dangerous to health in the long-term and is a problem for some pilots.'
        },
        {
            name: 'Antiphoton Visor',
            description: 'Designed to protect the wearer’s eyes from intense bursts of light, antiphoton visors are commonly found among breach teams and solar-forward operators. They are effective against flash weapons, intense UV light, and incidental charges from energy weapons.'
        },
        {
            name: 'Camo Cloth',
            description: 'A square of reactive material that slowly shifts to reflect the surrounding environment, enough to cover a human comfortably. The transition takes about 10 seconds and makes anything hidden underneath very difficult to spot.'
        },
        {
            name: 'Dataplating',
            description: 'Dataplating is a general term for any comm-linked jewelry, subdermal netting, wearable jaw, brow, or maxillary plates, etc., that allows subvocal communication and persistent heads-up and augmented reality displays without wearing a helm. Dataplates can quickly translate nearly any language, and allow users to communicate with each other all but silently.'
        },
        {
            name: 'Extra Rations',
            description: 'Pilot rations aren’t much better than their nautical forerunners – both are variants on hardtack and nutrient paste. Pilots often carry a stash of extra food, or luxuries like chocolate, coffee, alcohol, or preserved goods from their homeworld. These rations can be used to barter or boost morale.'
        },
        {
            name: 'Flexsuit',
            description: 'A strong base-layer suit that recycles water, generates nutrients, and adapts very rapidly to hostile environs, maintaining a stable condition and extending survivability. Flexsuit wearers can go for roughly a week without eating or drink thanks to the ambrosia paste generated by their suit before its systems are depleted; however, they don’t prevent feelings of hunger. Removing the suit for a day or two is enough to replenish its reserves. Flexsuits also maintain a steady temperature within acceptable parameters.'
        },
        {
            name: 'Subjectivity-Enhancement Suite',
            description: 'A subjectivity-enhancement suite is a set of cybernetic implants allowing users to hack systems without a rig. Users of these suites blend the organic with the synthetic, gaining the ability to extrude implanted universal-plug cables from within their body to make hardline connections with terminals. <br>When plugged in, users can access a comprehensive, fully interactive alternate-reality interface with direct omninet access, making navigating – or hacking – local and networked systems as easy as wishing it so (of course, you must be careful: by opening up your mind to the digital, you may face dangers other, less enhanced people are ignorant of).'
        },
        {
            name: 'Infoskin',
            description: 'A reactive, synthetic polymer with advanced qualities, infoskin bonds quickly to real skin and hair. Once applied, it responds to electronic signals delivered by linked software, rapidly changing its color and texture – even contorting and distorting its form – allowing wearers to make minor changes to their appearance. With infoskin, it’s a simple matter to alter facial features, hair color, or makeup patterns.'
        },
        {
            name: 'Omnihook',
            description: 'A portable – if bulky – omninet terminal that allows for communication, data transfer, and limited hot-spotting. Omnihooks are extremely valuable, although most mech squads have at least one. Tuning an omnihook requires a high level of skill, so they are usually mounted or carried by designated operators.'
        },
        {
            name: 'Personal Drone',
            description: 'Small, non-combat drones are a common sight in the field. They’re fairly noisy but can fly about a kilometer with good maneuverability before losing signal, relaying audio and visual information as they go.'
        },
        {
            name: 'Prosocollar',
            description: 'A collar-like device that fits snugly around its wearer’s neck, projecting a holographic image over their face and head. Prosocollars can change their wearer’s voice and scramble or change their appearance. The projection won’t stand up to close inspection, but it can easily fool electronic systems and distant observers.'
        },
        {
            name: 'Sleeping Bag',
            description: 'You can climb into your sleeping bag, gaining Immunity to burn, protection against vacuum, and enough air to last an hour. <br>Coming in a variety of sizes, sleeping bags are a field necessity. They’re designed to fold out from a hardsuit, fit within a mech’s cockpit, resist fire and changes in temperature, and – when necessary – seal against vacuum.'
        },
        {
            name: 'SSC Sylph Undersuit',
            description: 'Discovered on Acrimea IV, a biome cultivar world controlled by Smith-Shimano Corpro (SSC), the sylph is an organic lifeform that can seemingly survive in nearly any environment. Using breeding-analogous methods defined by established bioengineering doctrines, SSC developed the sylph undersuit – sterile, living sylphs grown as envelopes and fitted to their owners. The sylph bonds to its wearer, forming a symbiotic relationship: the sylph is sustained by the host’s waste products, in return protecting the host from a range of hostile environmental factors.<br><br>These semi-biological, skin-tight undersuits can be worn for extended periods. They are translucent, semi-liquid, and able to be stored when not in use, conforming to whatever container they are placed in. They clean the host’s body, aid natural healing processes, and eliminate waste. As desired, segments can become opaque, change color, or take on a new texture. Sylph undersuits can cover the host’s head, sealing against vacuum, providing protection against radiation, and filtering air or liquids, even providing the ability to breathe water for a limited time.'
        },
        {
            name: 'Sound System',
            description: 'Though their tactical utility is questionable, many pilots set up internal speaker systems in their cockpits. This gives them a clear line to their compatriots during combat, along with the ability to play music.'
        },
        {
            name: 'Wilderness Survival Kit',
            description: 'This kit contains many essentials for surviving in hostile environments: a rebreather, water filters, hardsuit patches, backup thermals, a bivouac kit, and so on.'
        },

    ]
}
export default PILOT_OPTIONS